### ISSUE TITLE
fix yarn build

### ISSUE THREAD

**Issue by pew** [meteocool/web#1]
the whole project should be deployed into `dist/` when `yarn build` is called. embarrassing workaround: `yarn && yarn build && mv public/* dist/`

**Comment by v4lli** [comment]
Abusing this issue for image upload, so better unsubscribe.

<img width="804" alt="Screen Shot 2021-01-16 at 16 46 00" src="https://user-images.githubusercontent.com/1577223/104816279-69104500-581a-11eb-8f8c-394b51d10c8f.png">
