### ISSUE TITLE
Import "About" text from old meteocool

### ISSUE THREAD

**Issue by v4lli** [meteocool/web#34]
We should import at least the contributors list and put it in the about modal.

@pew feel free to change "honorable mentions" to "pays for all of this crap so you can write 1 star reviews on the appstore for a completely free app"

**Comment by v4lli** [comment]
Also, the modal layout is broken on smaller (laptop) screens.

<img width="982" alt="Screen Shot 2021-01-14 at 02 46 50" src="https://user-images.githubusercontent.com/1577223/104533621-06992800-5613-11eb-93a6-b9143327688f.png">

**Comment by pew** [comment]
notion for more.
